name: Build & Deploy Spring App

on:
  push:
    branches:
      - main
jobs:
  build-deploy:
    name: Build and Deploy Spring Boot and Security
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17
          
      - name: list files
        run: ls -R
        
      - name: Unit Tests
        run: mvn -B test --file authentication-service/pom.xml

      - name: Build the Spring App
        run: |
          cd authentication-service
          mvn clean
          mvn -B package --file pom.xml
